// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAusdCyWdP7guiANMq5IS7jwmeCU2-z5jg',
    appId: '1:379681432845:web:539d22208c300aa834fc44',
    messagingSenderId: '379681432845',
    projectId: 'shoppinglist-9934f',
    authDomain: 'shoppinglist-9934f.firebaseapp.com',
    storageBucket: 'shoppinglist-9934f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJTuHr82LRqhmAtkeAAFguipgOCoWBNoc',
    appId: '1:379681432845:android:019fdb1f70272a6434fc44',
    messagingSenderId: '379681432845',
    projectId: 'shoppinglist-9934f',
    storageBucket: 'shoppinglist-9934f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6UdQUNuf-GKoLlj-mVtZ9j28aijNGBb4',
    appId: '1:379681432845:ios:eeec5e3902f5d6fb34fc44',
    messagingSenderId: '379681432845',
    projectId: 'shoppinglist-9934f',
    storageBucket: 'shoppinglist-9934f.appspot.com',
    iosBundleId: 'com.example.entregafinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6UdQUNuf-GKoLlj-mVtZ9j28aijNGBb4',
    appId: '1:379681432845:ios:4e313e1611cfebdf34fc44',
    messagingSenderId: '379681432845',
    projectId: 'shoppinglist-9934f',
    storageBucket: 'shoppinglist-9934f.appspot.com',
    iosBundleId: 'com.example.entregafinal.RunnerTests',
  );
}
